# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Fioctl < Formula
  desc "A simple tool to interact with the Foundries.io REST API for managing a Factory."
  homepage "https://foundries.io"
  version "0.1.32"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/matthewcroughan/fioctl/releases/v0.1.32/fioctl_0.1.32_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "ade3fe8b4e3d8b53a95f0adaf465da12546f9b2997452980608f82f8dec67a8f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/matthewcroughan/fioctl/releases/v0.1.32/fioctl_0.1.32_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "70afe57079720ff56120bb6f872e84f16fc8112001e4f297629a335e753eee18"
    end
  end
  
  depends_on "git"
  depends_on "zsh" => :optional

  def install
    bin.install "fioctl"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
