# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Fioctl < Formula
  desc "A simple tool to interact with the Foundries.io REST API for managing a Factory."
  homepage "https://foundries.io"
  version "0.1.33"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/matthewcroughan/fioctl/releases/v0.1.33/fioctl_0.1.33_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "b2830673310b03b9562c97f55bc0813747ac91e231252d3dc5b1f5d3c9fab83e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/matthewcroughan/fioctl/releases/v0.1.33/fioctl_0.1.33_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "71c3576745b53ec3d8a98768eafe1444d2a139c557137ae0766670a591f6c914"
    end
  end
  
  depends_on "git"
  depends_on "go"
  depends_on "zsh" => :optional

  def install
    bin.install "fioctl"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/fioctl -v"
  end
end
