# This file was generated by GoReleaser. DO NOT EDIT.
class Fioctl < Formula
  desc "A simple tool to interact with the Foundries.io REST API for managing a Factory."
  homepage "https://foundries.io"
  version "0.1.38"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/matthewcroughan/fioctl/releases/download/v0.1.38/fioctl_0.1.38_Darwin_x86_64.tar.gz"
    sha256 "ba115e968dc61d6777206ed13918c074694176069e876df5ae9cee9d1d6da1db"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "http://github.com/matthewcroughan/fioctl/releases/download/v0.1.38/fioctl_0.1.38_Linux_x86_64.tar.gz"
      sha256 "eb23ad8ce01123c3fad32328360a7866f97f62d32faf13020f2869d85f8234c6"
    end
  end
  
  depends_on "git"
  depends_on "zsh" => :optional

  def install
    bin.install "fioctl"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/fioctl -v"
  end
end
